version: "3.8"

services: 
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.dockerfile
        image: nginx
        ports: 
            - 8082:80
        links:
            - fpm
        volumes: 
            - ./app:/var/www/developstoday_test.com
            - ./docker/xdebug.conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        environment:
            PHP_IDE_CONFIG: "serverName=developstoday_test.com"

    fpm:
        build:
            context: ./
            dockerfile: docker/fpm.dockerfile
        volumes: 
            - ./app:/var/www/developstoday_test.com
            - ./docker/xdebug.conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        environment:
            PHP_IDE_CONFIG: "serverName=developstoday_test.com"
        links: 
            - postgresql


    postgresql:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=root
            - POSTGRES_DB=postgres
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            -   ./docker/sqldatadir:/var/lib/postgresql/data/pgdata

                
