version: "3.8"

services: 
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.dockerfile
        image: nginx
        ports: 
            - 8082:80
        links:
            - fpm
        volumes: 
            - ./app:/var/www/developstoday_test.com
            - ./docker/xdebug.conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        environment:
            PHP_IDE_CONFIG: "serverName=developstoday_test.com"

    fpm:
        build:
            context: ./
            dockerfile: docker/fpm.dockerfile
        volumes: 
            - ./app:/var/www/developstoday_test.com
            - ./docker/xdebug.conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        environment:
            PHP_IDE_CONFIG: "serverName=developstoday_test.com"
        links: 
            - postgresql


    postgresql:
        image: postgres
        ports:
            - 3306:3306
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=laravel_test_1
        volumes:
            -   ./docker/sqldatadir:/var/lib/postgresql/data/pgdata


#    mailer:
#        image: tophfr/mailcatcher
#        ports:
#            - 1080:80
#            - 1081:25

                
